### ISSUE TITLE
Listed on Khronos Group Repo?

### ISSUE THREAD

**Issue by johanos** [magicien/GLTFSceneKit#12]
Would you mind putting this project on the https://github.com/KhronosGroup/glTF read.me under the languages section for swift 

(I can try to do that too if you want) 

that way it gets more visibility! its a good project.

**Comment by magicien** [comment]
Thank you for your suggestion!
I'm going to send a pull request.

**Comment by magicien** [comment]
The pull request was merged! KhronosGroup/glTF#1174

**Comment by johanos** [comment]
Yay!
