### ISSUE TITLE
JOINTS_1 and WEIGHTS_1 support

### ISSUE THREAD

**Issue by ddnn55** [magicien/GLTFSceneKit#21]
I have a model where `attributes` on line https://github.com/magicien/GLTFSceneKit/blob/32a6c9ad2bfea9fbb10fc61c89e0e8d27d274a8f/Source/Common/GLTFUnarchiver.swift#L1066 contains keys `JOINTS_0` and `JOINTS_1` and `WEIGHTS_0` and `WEIGHTS_1`, but it seems GLTFSceneKit only supports `JOINTS_0` and `WEIGHTS_0`.

Is this a shortcoming of SceneKit itself? Or of GLTFSceneKit?

**Comment by gimlids** [comment]
Model: https://drive.google.com/file/d/1X1L9FUuEKEP13HrMFxKmQmH5RVF7W0Jy/view?usp=sharing

**Comment by magicien** [comment]
Merged #23. Thanks!
