### ISSUE TITLE
Material Names not retained

### ISSUE THREAD

**Issue by nikunjarora12345** [magicien/GLTFSceneKit#29]
Materials created are nameless. Is there a way to retain the material names from GLTF file?

**Comment by ennikin-skywalker** [comment]
I have the same problem. A quick solution for me:
[https://github.com/magicien/GLTFSceneKit/blob/fb897204356f972b724bf6ed4011df6a29d8b766/Source/Common/GLTFUnarchiver.swift#L956](url)

Add: `material.setValue(glMaterial.name, forKey: "name")`

**Comment by nikunjarora12345** [comment]
Thanks it works. I'll create a pull request for this.
