### ISSUE TITLE
SCNSkinner:  “there must be the same number of bone weights and bone indices”

### ISSUE THREAD

**Issue by amradawi** [magicien/GLTFSceneKit#30]
Running into an issue while rendering a gltf file through GLTFSceneKit. I've verifed that the file loads and animates through Bablyon.js, Cesium, Three.js but it is not working with SceneKit. more specifically I am getting this error on this line:

`let skinner = SCNSkinner(baseGeometry: baseGeometry, bones: joints, boneInverseBindTransforms: boneInverseBindTransforms, boneWeights: boneWeights, boneIndices: boneIndices)` in GLTFUnarchiver.swift

Any ideas how to fix it ?

**Comment by zhangguozhong** [comment]
Did you solve this problem? How to solve it?
