### ISSUE TITLE
lightingEnvironment rendering problem

### ISSUE THREAD

**Issue by magicien** [magicien/GLTFSceneKit#8]
I realized when I use SCNScene.lightingEnvironment, some models are rendered wrongly.
Fortunately, I can get the full shader source with Metal debugger. Let's check what is wrong.

[shader.metal.txt](https://github.com/magicien/GLTFSceneKit/files/1533328/shader.metal.txt)

![waterbottle](https://user-images.githubusercontent.com/1047810/33636277-555c6cb2-d9d0-11e7-8eed-12cd8bef3d05.png)
![barramundifish](https://user-images.githubusercontent.com/1047810/33636279-58d6bb5e-d9d0-11e7-9319-a024f3e60d88.png)
![boombox](https://user-images.githubusercontent.com/1047810/33636282-5a291c86-d9d0-11e7-82cc-0fac398b20e7.png)

**Comment by johanos** [comment]
Its the occlusion maps, for some reason its getting set to 5000

![image](https://user-images.githubusercontent.com/6535806/33666395-d84dab12-da67-11e7-824d-9c5c20492883.png)

but if we set it back down to 1 its looking good again. 

![image](https://user-images.githubusercontent.com/6535806/33666424-efc0937c-da67-11e7-82f5-a9bd67331dc7.png)

**Comment by magicien** [comment]
Genius!
I thought the default value of ambientOcclusion.intensity was 1000.
I fixed the calculation and it looks beautiful now.
Thank you so much!

![waterbottle_fixed](https://user-images.githubusercontent.com/1047810/33675511-a9382adc-da67-11e7-8fd8-e213fd034879.png)
![barramundifish_fixed](https://user-images.githubusercontent.com/1047810/33675525-b3aa682c-da67-11e7-954e-a26e2f0b4802.png)
![boombox_fixed](https://user-images.githubusercontent.com/1047810/33675523-b18b37ba-da67-11e7-88f4-2ac0393c05f3.png)
